#ifndef INTERNAL_RESISTANCE_H
#define INTERNAL_RESISTANCE_H

#include "definitions.h"

enum IRState {
    IR_STATE_IDLE,
    IR_STATE_START,
    IR_STATE_MEASURE_UNLOADED,
    IR_STATE_WAIT_UNLOADED,
    IR_STATE_GENERATE_PAIRS,
    IR_STATE_MEASURE_LOADED_UNLOADED,
    IR_STATE_MEASURE_PAIRS,
    IR_STATE_FINISH
};

void measureInternalResistanceStep();

#endif
