#ifndef CONFIG_H
#define CONFIG_H

// --- Hardware Pin Definitions ---
#define IR_RECEIVE_PIN 15
#define PWM_PIN 19
#define THERMISTOR_PIN_1 36
#define THERMISTOR_VCC_PIN 35
#define CURRENT_SHUNT_PIN 34
#define VOLTAGE_READ_PIN 39

// --- PWM Configuration ---
#define PWM_FREQUENCY 5000
#define PWM_RESOLUTION_BITS 8
#define MAX_DUTY_CYCLE ((1 << PWM_RESOLUTION_BITS) - 1)

// --- ADC Configuration ---
#define THERMISTOR_PIN_1_ATTENUATION ADC_ATTEN_DB_11
#define THERMISTOR_PIN_1_OVERSAMPLING 16
#define THERMISTOR_VCC_ATTENUATION ADC_ATTEN_DB_11
#define THERMISTOR_VCC_OVERSAMPLING 16
#define VOLTAGE_ATTENUATION ADC_ATTEN_DB_11
#define VOLTAGE_OVERSAMPLING 16
#define CURRENT_SHUNT_ATTENUATION ADC_ATTEN_DB_0
#define CURRENT_SHUNT_OVERSAMPLING 16


// --- Thermistor & Temperature Sensor Configuration ---
#define THERMISTOR_NOMINAL_RESISTANCE 10000
#define THERMISTOR_BETA_COEFFICIENT 3950
#define THERMISTOR_SERIES_RESISTOR 10000
#define NOMINAL_TEMPERATURE 25.0

// --- Current & Voltage Measurement Configuration ---
#define CURRENT_SHUNT_RESISTANCE 2.5f
#define MAIN_VCC_RATIO 2.0
#define CURRENT_SHUNT_PIN_ZERO_OFFSET 75
#define MEASURABLE_CURRENT_THRESHOLD 0.005f // 5mA

// --- Application Timing and Delays (in milliseconds) ---
#define PLOT_UPDATE_INTERVAL_MS 2000
#define PLOT_DATA_UPDATE_INTERVAL 1000
#define IR_HANDLE_INTERVAL_MS 500
#define CHARGING_HOUSEKEEP_INTERVAL 150
#define BUILD_CURRENT_MODEL_DELAY 200
#define IR_STABILIZATION_DELAY 2000
#define IR_UNLOADED_DELAY 6000

// --- Plotting & Display Configuration ---
#define PLOT_WIDTH 320
#define PLOT_HEIGHT (216 - 3)
#define PLOT_X_START 0
#define PLOT_Y_START 0
#define MAX_DATA_POINTS PLOT_WIDTH

#endif // CONFIG_H