#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

// --- Pin Definitions ---
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define THERMISTOR_PIN_1 36
#define THERMISTOR_PIN_1_ATTENUATION ADC_ATTEN_DB_11
#define THERMISTOR_PIN_1_OVERSAMPLING 16
#define THERMISTOR_VCC_PIN 35
#define THERMISTOR_VCC_ATTENUATION ADC_ATTEN_DB_11
#define THERMISTOR_VCC_OVERSAMPLING 16
#define VOLTAGE_READ_PIN 39
#define VOLTAGE_ATTENUATION ADC_ATTEN_DB_11
#define VOLTAGE_OVERSAMPLING 16
#define CURRENT_SHUNT_PIN 34
#define CURRENT_SHUNT_ATTENUATION ADC_ATTEN_DB_0
#define CURRENT_SHUNT_OVERSAMPLING 16
#define PWM_PIN 19
#define IR_RECEIVE_PIN 15

// --- PWM Settings ---
#define PWM_FREQUENCY 1000
#define PWM_RESOLUTION_BITS 8
#define PWM_MAX_DUTY_CYCLE ((1 << PWM_RESOLUTION_BITS) - 1)

// --- Thermistor and ADC configuration ---
#define MAIN_VCC_RATIO 2.0
#define CURRENT_SHUNT_RESISTANCE 2.5f
#define CURRENT_SHUNT_PIN_ZERO_OFFSET 75
#define VOLTAGE_UPDATE_INTERVAL_MS 250

#endif // CONFIG_H